language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t silkyng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true silkyng/docker-react npm run test